### ISSUE TITLE
documentation pages, html format issue

### ISSUE THREAD

**Issue by tst2005** [stepelu/lua-xsys#2]
Found in the http://scilua.org/xsys.html page

The following sample ...

```
local totrim = "  LuaJIT "
print("<"..totrim..">")                   --> <  LuaJIT >
print("<"..xsys.string.trim(totrim)..">") --> 
```

... should be displayed ...

```
local totrim = "  LuaJIT "
print("<"..totrim..">")                   --> <  LuaJIT >
print("<"..xsys.string.trim(totrim)..">") --> <LuaJIT>
```

The missing `<LuaJIT>` is due to a html format issue.
All `<` and `>` must be transformed to `&lt;` and `&gt;`

You should see all issue in [this report](https://validator.w3.org/nu/?doc=http%3A%2F%2Fscilua.org%2Fxsys.html)

Best Regards,

**Comment by stepelu** [comment]
I thought that https://github.com/google/code-prettify would handle this.

I tried with a javascript solution to escape all the problematic characters, but this results in code-prettify printing the escapes....that's possibly due to to the two being executed in wrong order.

I'll look into it as soon as I have some time, thank your for reporting.

**Comment by stepelu** [comment]
Forgot about this one, this is solved in the new version of the website.
